---
language: python
python:
  - "2.7"

# enable building on container-based infrastructure
before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


  # install dependencies
  - CFLAGS="-O0" pip install -e .[native]
  # install test dependencies
  - CFLAGS="-O0" pip install coveralls
  - python setup.py test
script:
  - python setup.py nosetests
after_script:
  - coveralls
 #2017-09-14 12:27:22 modified at 0